apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - elasticsearch.yaml
  - kibana.yaml
  - network/baseline
  - network/elasticsearch
  - network/kibana
